aabrowser/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('aabrowser.views',
    (r'^srt/$', 'srt'),

    # The home page redirects to the most recent changes
    url('^$', 'home', {}, name='aa-resources'),

    url(r'^search/$', 'search', {}, name='aa-search'),
    url(r'^add/$', 'add', {}, name='aa-add'),
    url(r'^resources/(?P<id>\d+)/$', 'resource', {}, name='aa-resource'),
    url(r'^resources/(?P<id>\d+)/annotate/$', 'resource_annotate'),
    url(r'^resources/(?P<id>\d+)/position/$', 'resource_position'),
    url(r'^resources/(?P<id>\d+)/size/$', 'resource_size'),
    url(r'^resources/(?P<id>\d+)/delete/$', 'resource_delete'),
    url(r'^resources/info/$', 'resource_info'),

    # Order resources by...
    url(r'^recent/$', 'resources', {'ordering': '-db_lastmodified'}, \
            name='aa-recent'),

    # Filter resources by type
    url(r'^video/$', 'resources', {'rtype': 'video'}, name='aa-video'),
    url(r'^audio/$', 'resources', {'rtype': 'audio'}, name='aa-audio'),
    url(r'^image/$', 'resources', {'rtype': 'image'}, name='aa-image'),
    url(r'^html/$', 'resources', {'rtype': 'html'}, name='aa-html'),
    url(r'^text/$', 'resources', {'rtype': 'text'}, name='aa-text'),

    url(r'^annotations/(?P<id>\d+)/$', 'annotation', {}, name='aa-annotation'),
    url(r'^annotations/(?P<id>\d+)/position/$', 'annotation_position', {}, \
            name='aa-annotation-position'),
    url(r'^annotations/(?P<id>\d+)/size/$', 'annotation_size', {}, \
            name='aa-annotation-size'),
    url(r'^annotations/(?P<id>\d+)/delete/$', 'annotation_delete', {}, \
            name='aa-annotation-delete'),
    url(r'^annotations/(?P<id>\d+)/export/srt/$', 'annotation_export', {}, \
            name='aa-annotation-export-srt'),
    url(r'^annotations/(?P<id>\d+)/export/audacity/$', 'annotation_export', \
            {'template': 'annotation.audacity.txt'}, \
            name='aa-annotation-export-audacity'),
    url(r'^annotations/(?P<id>\d+)/import/audacity/$', \
            'annotation_import_audacity',  {}, \
            name='aa-annotation-import-audacity'),

    url(r'^linktool/$', 'linktool', {}, name='aa-linktool'),
    url(r'^linktool/search/$', 'linktool_search', {}, \
            name='aa-linktool-search'),

    url(r'^tag/edit/(?P<name>.+)/$', 'tag', {}, name='aa-tag-edit'),
    url(r'^tag/rename/(?P<name>.+)/$', 'tag_rename', {}, name='aa-tag-rename'),
    url(r'^replace/$', 'searchandreplace', {}, name='aa-searchandreplace'),
    url(r'^tagstool/$', 'tagstool', {}, name='aa-tagstool'),
    url(r'^tags/$', 'tags', {}, name='aa-tags'),
    url(r'^tags/(?P<names>.+)/$', 'playlist', name='aa-playlist'),
)

aabrowser/models/Resource.py
# This file is part of Active Archives.
# Copyright 2006-2011 the Active Archives contributors (see AUTHORS)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# Also add information on how to contact you by electronic and paper mail.


import datetime
import mimetypes
import os
import re
import urllib
import urllib2
import urlparse
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models
from ResourceOpener import ResourceOpener


# look up a resource by URL
# reload/refresh/check a resource
# would like ability to do sniffing without necessarily involving models
urlescape = re.compile("%[A-F0-9][A-F0-9]", re.I)


def getResource(url, check=False, reload=False, download=False):
    """
    default (no options):
      only use network if resource is not in db
      if resource is in database, do nothing (return existing resource) -- no
      network activity
      else: get/sniff/create
    check:
      conditional get: in case of 304, only updates last_contact timestamp
    reload:
      same as get: check resource, don't accept 304
    download:
      same as get + attempts to download file
    """

    # Returns Resource, StatusCode
    #   status = None:  check==False and resource exists
    #   Resource may be None if resource is unknown & a connection error occurs

    if reload:
        check = True  # reload implies check
    if download:
        check = True  # download implies check
        reload = True

    try:
        res = Resource.objects.get(url=url)
        # Resource exists
        if not check:
            return res, None
        try:
            data = ResourceOpener(url)
            if reload:
                data.get()  # prevent a 304
            else:
                data.get(res.last_modified_raw, res.etag)

            # print data, data.status

            if data.status == 304:
                # if DEBUG:
                #     print "Resource.getURL: 304 - returning resource as is"
                # Resource is unchanged, return immediately
                res.last_contact = datetime.datetime.now()
                res.save()
                return res, data.status

            contentcls = classFromRequest(data)
            content = res.content

            # print "contentcls", contentcls, content
            # print "url: %s, content: %s, contentcls: %s" % (url, str(content), str(contentcls))
            if (content and content.__class__ != contentcls) \
                    or (not content and contentcls):
                    # CLASS HAS CHANGED
                    res.content = None
                    if content:
                        content.delete()
                    if contentcls:
                        res.content = instantiateResourceClass(contentcls, \
                                data, res)
                        res.save()
            else:
                # Update the resource (no change to class)
                res.syncRequest(data)

        # In error cases, return the known resource (untouched), plus the error
        # code
        except urllib2.HTTPError, e:
            return res, e.code
        except urllib2.URLError, e:
            return res, e.reason

    except Resource.DoesNotExist:
        # NEW RESOURCE
        try:
            data = ResourceOpener(url)
            data.get()
            res = Resource.fromRequest(data)
            contentclass = classFromRequest(data)
            if contentclass:
                res.content = instantiateResourceClass(contentclass, data, res)
                res.save()

        except urllib2.HTTPError, e:
            return None, e.code
        except urllib2.URLError, e:
            return None, e.reason

    if res and download:
        res.download()

    return res, data.status


def classFromRequest(data):
    """
    Maps the contents of a URL to a ResourceContent class

    Returns: subclass of ResourceContent
    Modifies: data

    Performs a depth first search (down the class hierarchy of ResourceSniffer)
    to determine the best candidate for instantiating the Resource.  Calls
    "sniff" method of subclasses, when a subclass returns True: sniff will be
    called for each of it's subclasses The last class to have returned True
    wins The data dictionary allows detection data to be accumulated and
    possibly shared by the subclasses to do efficient detecting and/or eventual
    instantiation.
    """

    # DEPTH FIRST SEARCH OF SUBCLASSES TO FIND MOST SPECIFIC MATCHING
    # SUBCLASS...
    sniffcls = ResourceSniffer
    klass = None
    while True:
        oldsniffcls = sniffcls
        for subsniffcls in sniffcls.__subclasses__():
            k = subsniffcls().sniff(data)
            if k:
                klass = k
                sniffcls = subsniffcls
                break
        if sniffcls == oldsniffcls:
            break
    return klass

#################################
# ResourceSniffer
#
# Subclasses of ResourceSniffer allow mappings to specific Resource "content"
# models
#


def instantiateResourceClass(klass, data, resource):
    ret = klass(resource=resource)
    ret.syncRequest(data)
    ret.save()
    return ret


class ResourceSniffer(object):
    def sniff(cls, data):
        """ should return a model class if it fits """
        return None

#################################
# Resource

RESOURCE_TYPES = (
    ('audio', 'audio'),
    ('video', 'video (no audio)'),
    ('audio/video', 'video'),
    ('image', 'image'),
    ('html', 'html'),
    ('text', 'text'),
    ('', '')
)

RESOURCE_STATUS = (
    ('active', 'active'),
    ('default', 'default'),
    ('inactive', 'inactive')
)


class Resource(models.Model):
    """
    has understanding of local file / cacheability
    calls syncWithFile on content classes as appropriate
    """

    @classmethod
    def fromRequest(cls, data):
        ret = Resource(url=data.url)
        ret.syncRequest(data)
        return ret

    class Meta:
        app_label = "aabrowser"

    status = models.CharField(
            max_length=16,
            choices=RESOURCE_STATUS,
            default="default",
    )
    url = models.URLField(
            verify_exists=False,
    )
    filename = models.CharField(
            max_length=255,
            blank=True,
    )
    hostname = models.CharField(
            max_length=255,
            blank=True,
    )
    content_type = models.CharField(
            max_length=255,
            default="",
            blank=True,
    )
    content_length = models.IntegerField(
            default=0,
    )
    charset = models.CharField(
            max_length=64,
            default="",
            blank=True,
    )
    last_modified_raw = models.CharField(
            max_length=255,
            default="",
            blank=True,
    )
    last_modified = models.DateTimeField(
            null=True,
            blank=True,
    )
    etag = models.CharField(
            max_length=255,
            default="",
            blank=True,
    )
    object_type = models.ForeignKey(
            ContentType,
            null=True,
            blank=True,
    )
    object_id = models.PositiveIntegerField(
            null=True,
            blank=True,
    )
    content = generic.GenericForeignKey(
            'object_type',
            'object_id',
    )
    last_contact = models.DateTimeField(
            null=True,
            blank=True,
    )
    last_downloaded = models.DateTimeField(
            null=True,
            blank=True,
    )
    rtype = models.CharField(
            max_length=255,
            choices=RESOURCE_TYPES,
            blank=True,
    )
    top = models.IntegerField(
            default=0,
    )
    left = models.IntegerField(
            default=0,
    )
    width = models.IntegerField(
            default=320,
    )
    height = models.IntegerField(
            default=320,
    )
    db_creator = models.ForeignKey(
            User,
            null=True,
            blank=True,
            related_name="resources_as_creator",
    )
    db_created = models.DateTimeField(
            auto_now_add=True,
    )
    db_lastmodifier = models.ForeignKey(
            User,
            null=True,
            blank=True,
            related_name="resources_as_lastmodifier",
    )
    db_lastmodified = models.DateTimeField(
            auto_now=True,
    )

    def __unicode__(self):
        return self.url

    @models.permalink
    def get_absolute_url(self):
        return ('aa-resource', (str(self.id),))

    def syncRequest(self, data):
        parts = urlparse.urlparse(self.url)
        (_, self.filename) = os.path.split(parts.path)
        self.hostname = parts.hostname
        self.content_type = data.content_type
        self.charset = data.charset
        self.content_length = data.content_length
        self.etag = data.etag
        self.last_modified_raw = data.last_modified_raw
        self.last_modified = data.last_modified
        self.last_contact = datetime.datetime.now()
        self.save()

        # pass this on to the content object!
        content = self.content
        if content:
            content.syncRequest(data)

            # DELETE THE THUMBNAIL IF ZERO LENGTH
            tp = content.thumbnail_source()

aabrowser/templates/aa_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:foaf="http://xmlns.com/foaf/0.1/"
  xmlns:vcard="http://www.w3.org/2006/vcard/ns#"
  xmlns:biografr="http://biografr.com/ontology#"
  xmlns:aa="http://activearchives.org/terms#"
>

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title>{% block title %}active archives{% endblock %}</title>

    <!--JQUERY-->
    <link rel="stylesheet" href="{{MEDIA_URL}}aabrowser/lib/jquery/jquery-ui.css" type="text/css" charset="utf-8" />
    <script src="{{MEDIA_URL}}aabrowser/lib/jquery/jquery.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/lib/jquery/jquery-ui.js" type="text/javascript" charset="utf-8"></script>	

    <!--RDFQUERY-->
    <script src="{{MEDIA_URL}}aabrowser/lib/rdfquery/jquery.rdfquery.rules.min-1.0.js" type="text/javascript" charset="utf-8"></script>	

    <!--FLOWPLAYER-->
    <script src="{{MEDIA_URL}}aabrowser/lib/swfobject/swfobject.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/lib/flowplayer/flowplayer.js" type="text/javascript" charset="utf-8"> </script>
    <link rel="flowplayer" href="{{MEDIA_URL}}aabrowser/lib/flowplayer/flowplayer.swf" />
    <link rel="flowplayeraudio" href="{{MEDIA_URL}}aabrowser/lib/flowplayer/flowplayer.audio.swf" />
    <link rel="flowplayerpseudostreaming" href="{{MEDIA_URL}}aabrowser/lib/flowplayer/flowplayer.pseudostreaming.swf" />

    <!--OTHER LIB-->
    <script src="{{MEDIA_URL}}aabrowser/lib/shortcut.js" type="text/javascript" charset="utf-8"></script>	

    <!--AA-->
    <script src="{{MEDIA_URL}}aabrowser/jquery.caret.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.log.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.timecode.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.delayedaction.js" type="text/javascript" charset="utf-8"></script>	

    <script src="{{MEDIA_URL}}aabrowser/jquery.timeline.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.animatedsetter.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.ui.autoscrollable.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.ui.timedtext.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.ui.playable.js" type="text/javascript" charset="utf-8"></script>	
    <script src="{{MEDIA_URL}}aabrowser/jquery.ui.playlist.js" type="text/javascript" charset="utf-8"></script>	

    <!--CSS-->
    <link rel="stylesheet" href="{{MEDIA_URL}}aabrowser/jquery.aascrubber.css" type="text/css" charset="utf-8" />
    <link rel="stylesheet" href="{{MEDIA_URL}}aabrowser/styles.css" type="text/css" charset="utf-8" />

    {% block extrahead %}{% endblock extrahead %}

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            
            // SIDEBAR
            (function () {
                var c = $("#sidebar_content");
                var stayOpen = c.is(":visible");
                $("#sidebar_content").resizable({
                    handles: "e"
                });
                $("#sidebar_toggle").click(function () {
                    if (!c.is(":visible")) {
                        c.show();
                        stayOpen = true;
                    } else {
                        c.hide();
                        stayOpen = false;
                    }
                });
                var hider = $.delayedaction(function () {
                    c.hide();
                }, 500);
                $("#sidebar_rollover").mouseover(function () {
                    if (!c.is(":visible")) {
                        c.show();
                    }
                }).mouseout(function () {
                    if (!stayOpen) hider.do_soon();
                });
                
                c.mouseover(function () {
                    hider.cancel();
                }).mouseout(function () {
                    if (!stayOpen) hider.do_soon();
                });
                
                
            })();

    /* TAGSTOOL */
    /* Show/Hide tags of a tag category */
    function activate_tagstool() {
        $("#tagstool .tagcatname").each(function () {
            var tagcat = $(this).closest(".tagcat");
            var body = $(".tagcatbody", tagcat);
            $(this).toggle(
                function(){ body.show('fast');},
                function(){ body.hide('fast');}
            );
        });
        // this makes sure that the tags are draggable (drag & drop into an annotation edit textarea)
        $("#tagstool a.tagtool").each(function () {
            $(this).draggable({helper: 'clone'});
        });
    }
    activate_tagstool();

    $(".tagtool").mouseover(function(){
        $('.tagtooledit', $(this)).css('display', 'inline');
    });    
    $(".tagtool").mouseout(function(){
        $('.tagtooledit', $(this)).css('display', 'none');
    });    

    /*
    $("#tagstool a.reload_button").click(function () {
        var href = $(this).attr("href");
        var body = $(".tagstoolbody", "#tagstool");
        body.load(href, function () {
            activate_tagstool();
        });
        
        return false;   
    });
    */


        });
    </script>
</head>

<body>
{%  load markup %}
<div id="sidebar">
        <div id="sidebar_content">
        {% block sidebar %}
            {% include 'sidebar.html' %}
        {% endblock sidebar %}

        {% block tagstool %}
            {% include 'tagstool.html' %}
        {% endblock tagstool %}
        </div><!--.content-->
    <div id="sidebar_rollover"></div>
    <div id="sidebar_toggle"></div>
</div><!--sidebar-->

<div id="header">
    <table>
        <tr>
        <!-- Add-ressource bar -->
        <td id='url-bar'>
        <form method="post" action="{% url aa-add %}">
            {% csrf_token %}

            <div id="aa_add_input">
                <input type="text" name="s" value="{% block searchbar %}{{ navurl }}{% endblock %}" />
            </div>

            <div id="aa_add_submit">
                <input type="submit" name="_submit" value="ok" />
            </div>

            {% if results %}
                <div>result: {{ resource }} {{ status }}</div>
            {% endif %}

            {% if message %}
                <div class="message">{{ message|textile }}</div>
            {% endif %}
        </form>
        </td>

        {% block tools %}
        {% endblock %}
        </tr>
    </table>
</div>


<div id="scrollable">

{% block main %}
    <div id="content">
        {% block header %}{% endblock header %}

        {% block list %}
        {% endblock list %}
    </div>
{% endblock %}

</div>

{% block fixed %}
{% endblock %}

</body>
</html>

aabrowser/templates/aa_simple_base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>{%block title%}active archives{%endblock%}</title>
<link rel="stylesheet" href="{{MEDIA_URL}}aabrowser/lib/jquery/jquery-ui.css" type="text/css" charset="utf-8" />
<script src="{{MEDIA_URL}}aabrowser/lib/jquery/jquery.js" type="text/javascript" language="javascript" charset="utf-8"></script>	
<script src="{{MEDIA_URL}}aabrowser/lib/jquery/jquery-ui.js" type="text/javascript" language="javascript" charset="utf-8"></script>	
<link rel="stylesheet" href="{{MEDIA_URL}}aabrowser/styles.css" type="text/css" charset="utf-8" />
{%block extrahead%}
{%endblock%}
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

aabrowser/templates/annotation.html
{% load aamarkup %}
{% load markup %}
<div class="aa-playlist" data-resource="{{annotation.resource.url}}" data-id="{{annotation.id}}" style="top: {{annotation.top}}px; left: {{annotation.left}}px; width: {{annotation.width}}px; height: {{annotation.height}}px">
    {% for section in annotation.ssections %}
    <div class="aa-playlist-section" data-id="{{section.id}}" data-url="{%if section.resource %}{{section.resource.url}}{%else%}{{section.annotation.resource.url}}{%endif%}"{%if section.resource%} data-edit-url="{{section.resource.get_absolute_url}}"{%endif%}{%if section.start != None %} data-start="{{section.start}}"{%endif%}{%if section.end %} data-end="{{section.end}}"{%endif%}>
        {{section.source|aalinks|textile}}
        <textarea class="aa-playlist-section-source">{{section.source}}</textarea>
    </div>
    {% endfor %}
</div>

aabrowser/templates/annotation_import.html
{% extends "aa_simple_base.html" %}
{% block body %}
<h2>Import Audacity Labels</h2>
<div>Attach to resource: {{a.resource.url}}</div>
<form enctype="multipart/form-data" method="post" action="">{% csrf_token %}
{{form.as_table}}
<div>
    <input type="submit" value="import" />
</div>
</form>
{% endblock %}

aabrowser/templates/playlist.html
{% extends "resource.html" %}
{% load markup %}
{% load aamarkup %}

{% block resourcecontent %}
<div id="player"></div>
{% endblock %}

{% block resource_header %}
{% endblock resource_header %}

{% block annotations %}
{{ block.super }}
<div class="aa-playlist" data-resource="{{resource.url}}" style="top: 50px; left: 50px; width: 320px; height: 400px">
    <div class="aa-playlist-section" data-url="{{resource.url}}">
        <h2>Automatic playlist</h2>
        <textarea class="aa-playlist-section-source"></textarea>
    </div>
    {% for section in playlist_sections %}
    <div class="aa-playlist-section" data-url="{{section.aresource.url}}" data-edit-url="{{section.aresource.get_absolute_url}}"{%if section.start != None %} data-start="{{section.start}}"{%endif%}{%if section.end %} data-end="{{section.end}}"{%endif%}>
        {{section.source|aalinks|textile}}
        <textarea class="aa-playlist-section-source">{{section.source}}</textarea>
    </div>
    {% endfor %}
</div>
{% endblock annotations %}

aabrowser/templates/resource_delete.html
{% extends "aa_simple_base.html" %}
{% load thumbnail %}

{% block body %}

<div style="width: 400px; background: #AAA; margin: auto auto;">
    {{resource.url}}

    {% if resource.thumbnail_source %}
    <img src="{% thumbnail resource.thumbnail_source 320x320 %}" />
    {% endif %}

    <div style="margin-top: 10px">
        Are you sure you want to delete this resource?

        <form method="post">{% csrf_token %} 
            <input name="_submit" type="submit" value="delete" />
            <input name="_submit" type="submit" value="cancel" />
        </form>
    </div>
</div>
{%endblock %}

aabrowser/templates/resource_description.html
{% load aamarkup %}
<div id='description'>
    {%if resource.rtype%}<span class='rtype'>{{resource.get_rtype_display}}</span> {%endif%}
    <a href="{% url aabrowser.views.resource resource.id %}">"{{resource.name}}"</a>,
    {% if resource.duration %} with duration {{resource.duration|secs2timecode}},{%endif%}
    added to the archive {{resource.db_created|date}} from <a href="{{resource.url}}">{{resource.hostname}}</a>.
    {%if resource.last_modified%}According to the server, this resource last changed {{resource.db_lastmodified|date}}.{%endif%}
</div>

aabrowser/templates/resources.html
{% extends "aa_base.html" %}


{% load aamarkup %}
{% load thumbnail %}


{% block extrahead %}{% endblock %}


{% block list %}
{% comment %}
    {% for resource in resources.object_list %}
        <div style="width:400px; clear: both; margin-bottom: 2em;">
            {% if resource.thumbnail_source %}
                <a style="display: block; float: left;" href="{% url aabrowser.views.resource resource.id %}">
                    <img src="{% thumbnail resource.thumbnail_source 160x160 %}" border="0" />
                </a>
            {% endif %}
            {% if resource.rtype %}<span style="background: black; color: white">{{ resource.get_rtype_display }}</span> {% endif %}
            <a href="{% url aabrowser.views.resource resource.id %}">
                "{{ resource.name }}"
            </a>,
            {% if resource.duration %} with duration {{ resource.duration|secs2timecode }},{% endif %}
            added to the archive {{ resource.db_created|date }} from <a href="{{ resource.url }}">{{ resource.hostname }}</a>.
            {% if resource.last_modified %}According to the server, this resource last changed {{ resource.last_modified|date }}.{%endif%}
            <p>
            This resource has {{ resource.annotations.count }} annotations.
            </p>
            <br style="clear:both;" />
        </div>
    {% endfor %}
{% endcomment %}
<table id="resource-list">
    <thead></thead>
    <tbody>
    {% for resource in resources.object_list %}
        <tr>
            {% if resource.thumbnail_source %}
            <td class="thumb_img">
                <a href="{% url aabrowser.views.resource resource.id %}">
                    <img src="{% thumbnail resource.thumbnail_source 160x160 %}" border="0" />
                </a>
            </td>
            <td class='thumb_info'>
            {% else %}
            <td class='thumb_info' colspan=2>
            {% endif %}
            
                {% include 'resource_description.html' %}
            
                <p>
                    This resource has {{resource.annotations.count}} annotations.
                </p>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if resources.has_previous %}
            <a href="?page={{ resources.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ resources.number }} of {{ resources.paginator.num_pages }}.
        </span>

        {% if resources.has_next %}
            <a href="?page={{ resources.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock %}

aabrowser/templates/search.html
{% extends "playlist.html" %}

aabrowser/templates/srt.html
{% extends "aa_base.html" %}
{% block body %}
<form method="post" action="">{% csrf_token %}
<div>
<textarea name="source" style="width: 320px; height: 240px">
</textarea>
</div>
<input type="submit" name="_submit" value="save" />
</form>
{%if srt%}
{{srt.unparse_xml}}
{% endif %}
{% endblock %}

aabrowser/templates/tag-edit.html
{% load markup %}
{% load thumbnail %}
{% load aamarkup %}
{% block body %}
<h2>{{tag.name}}</h2>

<!-- the tags editable bits -->
<form method="post" action="">
<table>
{{form.as_table}}
{% csrf_token %} 
</table>
<input type="submit" value="save" />
</form>

<!-- list of matching resources -->
{% for sectiontag in tag.sectiontag_set.all %}
<div style="float: left; width: 200px; height: 200px">
    {% with sectiontag.section as section %}
    {% with sectiontag.rel as rel %}
    {% with section.annotation.resource as resource %}
    <a href="{% url aa-resource resource.id %}">
        {% if rel %}As {{rel}} for:<br />{%endif %}
        {% if resource.thumbnail_source %}<img src="{% thumbnail resource.thumbnail_source 160x160 %}" border="0" /><br />{% endif %}
        {{section.annotation.resource}} 
    </a>
    <div class="timecodes">
        ({%if section.start != None %}{{section.start|secs2timecode}} --> {%if section.end != None %}{{section.end|secs2timecode}}{%endif%}{%else%}no timing{%endif%})
    </div>
    {% endwith %}
    {% endwith %}
    {% endwith %}
</div>
{% endfor %}

{% endblock %}